# Generated by Django 5.0.6 on 2026-07-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('smety', '0002_seed_bazacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapGrafika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Этап / работа')),
                ('edinica', models.CharField(default='м²', max_length=20, verbose_name='Ед. изм.')),
                ('plan_objem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='План, объём')),
                ('fact_objem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Факт, объём')),
                ('rascenka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расценка за ед., ₽')),
                ('plan_data_nachala', models.DateField(verbose_name='План: начало')),
                ('plan_data_okonchania', models.DateField(verbose_name='План: окончание')),
                ('poryadok', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('smeta_rabota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smety.smetarabota')),
            ],
            options={
                'verbose_name': 'Этап графика',
                'verbose_name_plural': 'График работ',
                'ordering': ['poryadok', 'plan_data_nachala', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('adres', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('zakazchik', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('master_otvetstvenny', models.CharField(blank=True, max_length=255, verbose_name='Ответственный мастер')),
                ('data_nachala', models.DateField(verbose_name='Дата начала')),
                ('data_okonchania_plan', models.DateField(verbose_name='Плановая дата окончания')),
                ('summa_dogovora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма договора, ₽')),
                ('avans_procent', models.PositiveSmallIntegerField(default=30, verbose_name='Аванс, %')),
                ('srok_oplaty_posle_akta_dney', models.PositiveSmallIntegerField(default=10, verbose_name='Срок оплаты после акта, дней')),
                ('garantiynoe_uderzhanie_procent', models.PositiveSmallIntegerField(default=5, verbose_name='Гарантийное удержание, %')),
                ('srok_vozvrata_garantii_dney', models.PositiveSmallIntegerField(default=365, verbose_name='Срок возврата гарантийного удержания, дней')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('completed', 'Сдан'), ('paused', 'Приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obekty', to='core.brigada', verbose_name='Бригада')),
                ('smeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obekty', to='smety.smeta', verbose_name='Смета-источник')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-data_sozdaniya'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Материал')),
                ('srok_proizvodstva_dney', models.PositiveSmallIntegerField(default=0, verbose_name='Срок производства, дней')),
                ('srok_dostavki_dney', models.PositiveSmallIntegerField(default=0, verbose_name='Срок доставки, дней')),
                ('bufer_dney', models.PositiveSmallIntegerField(default=4, verbose_name='Буфер, дней')),
                ('data_zakaza_fakt', models.DateField(blank=True, null=True, verbose_name='Дата заказа (факт)')),
                ('status', models.CharField(choices=[('ne_zakazan', 'Не заказан'), ('zakazan', 'Заказан'), ('v_puti', 'В пути'), ('na_obekte', 'На объекте')], default='ne_zakazan', max_length=20, verbose_name='Статус')),
                ('etap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialy', to='objekty.etapgrafika', verbose_name='Этап')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialy', to='objekty.objekt', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['etap__poryadok', 'nazvanie'],
            },
        ),
        migrations.AddField(
            model_name='etapgrafika',
            name='objekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapy', to='objekty.objekt', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='DvizhenieDeneg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnovanie', models.CharField(help_text='«Аванс» / «Акт за этап X»', max_length=255, verbose_name='Основание')),
                ('summa_nachislenie', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма начисления, ₽')),
                ('data_plan', models.DateField(verbose_name='Плановая дата')),
                ('data_fakt', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('ozhidaetsya', 'Ожидается'), ('polucheno', 'Получено'), ('prosrocheno', 'Просрочено')], default='ozhidaetsya', max_length=20, verbose_name='Статус')),
                ('etap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objekty.etapgrafika')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvizhenie_deneg', to='objekty.objekt', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Движение денег',
                'verbose_name_plural': 'Деньги от заказчика',
                'ordering': ['data_plan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiZapros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vopros', models.TextField(verbose_name='Вопрос')),
                ('otvet', models.TextField(verbose_name='Ответ')),
                ('demo_rezhim', models.BooleanField(default=False, verbose_name='Демо-режим (без ключа Anthropic)')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_zaprosy', to='objekty.objekt', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Запрос к AI-ассистенту',
                'verbose_name_plural': 'Запросы к AI-ассистенту',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='OplataMontajnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montajnik_fio', models.CharField(max_length=255, verbose_name='Монтажник (ФИО)')),
                ('rascenka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расценка за ед., ₽')),
                ('mesyats', models.DateField(verbose_name='Месяц (1-е число)')),
                ('plan_objem_mesyats', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Плановый объём за месяц')),
                ('fact_objem_mesyats', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактический объём за месяц')),
                ('oplacheno_sverh_grafika', models.BooleanField(default=False, verbose_name='Оплата сверх графика подтверждена')),
                ('summa_oplacheno', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Уже оплачено, ₽')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oplaty_montajnikov', to='objekty.objekt', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Оплата монтажнику',
                'verbose_name_plural': 'Оплата бригаде',
                'ordering': ['-mesyats', 'montajnik_fio'],
            },
        ),
        migrations.CreateModel(
            name='RashodMesyachny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesyats', models.DateField(verbose_name='Месяц (1-е число)')),
                ('sutochnye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Суточные, ₽')),
                ('arenda_kvartiry', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Аренда жилья, ₽')),
                ('oplata_mastera', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата мастера, ₽')),
                ('dolya_ofisa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доля офисных расходов, ₽')),
                ('prochee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прочее, ₽')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rashody', to='objekty.objekt', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Месячный расход',
                'verbose_name_plural': 'Расходы объекта',
                'ordering': ['-mesyats'],
            },
        ),
    ]
