# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('objekty', '0001_initial'),
        ('smety', '0002_seed_bazacen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['objekt', 'status'], name='objekty_mat_objekt__1bbe34_idx'),
        ),
        migrations.AddIndex(
            model_name='objekt',
            index=models.Index(fields=['brigada', 'status'], name='objekty_obj_brigada_31276b_idx'),
        ),
    ]
