# Generated by Django 5.0.6 on 2026-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekty', '0002_material_objekty_mat_objekt__1bbe34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oplatamontajnika',
            name='data_vyplaty',
            field=models.DateField(blank=True, help_text='Если не указана — 10-е число следующего месяца', null=True, verbose_name='Дата выплаты'),
        ),
    ]
