# Generated by Django 5.0.6 on 2026-07-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolosovayaKomanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='golos/', verbose_name='Аудио')),
                ('tekst_raspoznanny', models.TextField(blank=True, verbose_name='Распознанный текст')),
                ('pozicii_najdeno', models.PositiveIntegerField(default=0, verbose_name='Найдено позиций')),
                ('status', models.CharField(choices=[('obrabotan', 'Обработана'), ('oshibka', 'Ошибка')], default='obrabotan', max_length=20, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golosovye', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Голосовая команда',
                'verbose_name_plural': 'Голосовые команды',
                'ordering': ['-data'],
            },
        ),
    ]
