# Generated by Django 5.0.6 on 2026-07-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platezh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('tarif', models.CharField(choices=[('samozanyaty', 'Самозанятый'), ('brigadir', 'Бригадир'), ('pro', 'PRO')], max_length=20, verbose_name='Тариф')),
                ('status', models.CharField(choices=[('ozhidaet', 'Ожидает оплаты'), ('oplachen', 'Оплачен'), ('vozvrat', 'Возврат'), ('otmenen', 'Отменён')], default='ozhidaet', max_length=20, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('yookassa_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа в ЮKassa')),
                ('demo_rezhim', models.BooleanField(default=False, help_text='Платёж симулирован локально, реальных денег не было', verbose_name='Тестовый режим (без ключей ЮKassa)')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platezhi', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('mesyats', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('dokumenty_ispolzovano', models.PositiveIntegerField(default=0, verbose_name='Использовано документов')),
                ('raschety_ispolzovano', models.PositiveIntegerField(default=0, verbose_name='Использовано расчётов')),
                ('smety_ispolzovano', models.PositiveIntegerField(default=0, verbose_name='Использовано смет')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_trackers', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Счётчик лимитов',
                'verbose_name_plural': 'Счётчики лимитов',
                'unique_together': {('brigada', 'god', 'mesyats')},
            },
        ),
    ]
