# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='platezh',
            index=models.Index(fields=['brigada', '-data'], name='billing_pla_brigada_d4e03a_idx'),
        ),
        migrations.AddIndex(
            model_name='platezh',
            index=models.Index(fields=['yookassa_id'], name='billing_pla_yookass_3c337d_idx'),
        ),
    ]
