# Generated by Django 5.0.6 on 2026-07-14 16:40

import django.db.models.deletion
import fotoakty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_file', models.ImageField(upload_to=fotoakty.models.fotoakt_path, verbose_name='Фото')),
                ('watermark_text', models.CharField(blank=True, max_length=255, verbose_name='Водяной знак')),
                ('geo_lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('geo_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('podpis_snizu', models.CharField(blank=True, max_length=255, verbose_name='Подпись под фото')),
                ('data_zagruzki', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotoakty', to='documents.dokument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Фото акта',
                'verbose_name_plural': 'Фото-акты',
                'ordering': ['data_zagruzki'],
            },
        ),
    ]
