# Generated by Django 5.0.6 on 2026-07-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodpisZakazchika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(blank=True, max_length=32, unique=True, verbose_name='Токен ссылки')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Телефон подписанта')),
                ('ip_adres', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP подписанта')),
                ('kod_sms_hash', models.CharField(blank=True, max_length=255, verbose_name='Хеш СМС-кода')),
                ('soglasie', models.BooleanField(default=False, verbose_name='Согласие с условиями')),
                ('status', models.CharField(choices=[('ozhidaet', 'Ожидает подписания'), ('podpisano', 'Подписано'), ('otkloneno', 'Отклонено')], default='ozhidaet', max_length=20, verbose_name='Статус')),
                ('doc_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 документа')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('data_podpisi', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podpisi', to='documents.dokument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Подпись заказчика (ПЭП)',
                'verbose_name_plural': 'Подписи заказчиков (ПЭП)',
                'ordering': ['-data_sozdaniya'],
            },
        ),
    ]
