# Generated by Django 5.0.6 on 2026-07-11 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название бригады')),
                ('telefon', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон в формате +79991234567', regex='^\\+?7\\d{10}$')], verbose_name='Телефон')),
                ('rekvizity', models.TextField(blank=True, verbose_name='Реквизиты (ИНН, счёт и т.д.)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('tarif', models.CharField(choices=[('start', 'Старт'), ('samozanyaty', 'Самозанятый'), ('brigadir', 'Бригадир'), ('pro', 'PRO')], default='start', max_length=20, verbose_name='Тариф')),
                ('data_okonchaniya_tarifa', models.DateField(blank=True, null=True, verbose_name='Дата окончания тарифа')),
                ('data_registracii', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigada', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
                'ordering': ['-data_registracii'],
            },
        ),
    ]
