# Generated by Django 5.0.6 on 2026-07-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzlishekMateriala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=200, verbose_name='Материал')),
                ('kolvo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
                ('edinica', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед., ₽')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Регион / город')),
                ('opisanie', models.TextField(blank=True, verbose_name='Описание')),
                ('kontakt_telefon', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('status', models.CharField(choices=[('aktivno', 'Активно'), ('prodano', 'Продано / снято')], default='aktivno', max_length=20, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izlishki', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Излишек материала',
                'verbose_name_plural': 'Биржа излишков',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Otzyv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor_imya', models.CharField(max_length=120, verbose_name='Имя автора')),
                ('ocenka', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)')),
                ('tekst', models.TextField(verbose_name='Отзыв')),
                ('obekt', models.CharField(blank=True, max_length=200, verbose_name='Объект / город')),
                ('podtverzhden', models.BooleanField(default=False, verbose_name='Подтверждён (сделка через сервис)')),
                ('opublikovan', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otzyvy', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=200, verbose_name='Название заявки')),
                ('opisanie', models.TextField(verbose_name='Что нужно сделать')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Регион / адрес')),
                ('byudzhet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ориентировочный бюджет, ₽')),
                ('srok_do', models.DateField(blank=True, null=True, verbose_name='Отклики до')),
                ('status', models.CharField(choices=[('otkryt', 'Открыт'), ('zakryt', 'Закрыт')], default='otkryt', max_length=20, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendery', to='core.brigada', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TenderOtklik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Предложенная цена, ₽')),
                ('srok_dney', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок, дней')),
                ('kommentariy', models.TextField(blank=True, verbose_name='Комментарий')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otkliki', to='core.brigada', verbose_name='Бригада')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otkliki', to='marketplace.tender', verbose_name='Тендер')),
            ],
            options={
                'verbose_name': 'Отклик на тендер',
                'verbose_name_plural': 'Отклики на тендеры',
                'ordering': ['cena'],
                'unique_together': {('tender', 'brigada')},
            },
        ),
    ]
