# Generated by Django 5.0.6 on 2026-07-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChyornySpisok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Телефон')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ИНН')),
                ('prichina', models.CharField(max_length=255, verbose_name='Причина')),
                ('istochnik', models.CharField(choices=[('narod', 'Жалобы бригад'), ('arbitr', 'Арбитражные дела'), ('fns', 'ФНС / реестры')], default='narod', max_length=20, verbose_name='Источник')),
                ('kolvo_zhalob', models.PositiveIntegerField(default=1, verbose_name='Количество жалоб')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Запись чёрного списка',
                'verbose_name_plural': 'Чёрный список',
                'ordering': ['-kolvo_zhalob'],
            },
        ),
        migrations.CreateModel(
            name='ProverkaZakazchika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_poiska', models.CharField(choices=[('inn', 'По ИНН (юрлицо/ИП)'), ('telefon', 'По телефону (физлицо)')], max_length=10, verbose_name='Тип проверки')),
                ('znachenie', models.CharField(max_length=30, verbose_name='ИНН / телефон')),
                ('status_riska', models.CharField(choices=[('nizky', 'Низкий'), ('sredny', 'Средний'), ('vysoky', 'Высокий')], max_length=10, verbose_name='Уровень риска')),
                ('prichina', models.CharField(blank=True, max_length=255, verbose_name='Обоснование')),
                ('detali', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('demo_rezhim', models.BooleanField(default=False, verbose_name='Демо-режим')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proverki', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Проверка заказчика',
                'verbose_name_plural': 'Проверки заказчиков',
                'ordering': ['-data'],
            },
        ),
    ]
