# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('proverka', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proverkazakazchika',
            index=models.Index(fields=['brigada', '-data'], name='proverka_pr_brigada_29d432_idx'),
        ),
    ]
