# Generated by Django 5.0.6 on 2026-07-11 18:05

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('dogovor', 'Договор подряда'), ('akt_vkr', 'Акт выполненных работ (ВКР)'), ('raspiska', 'Расписка об авансе'), ('akt_priemki', 'Акт приёмки этапа')], max_length=20, verbose_name='Тип документа')),
                ('nomer', models.CharField(blank=True, max_length=30, verbose_name='Номер документа')),
                ('zakazchik', models.CharField(max_length=255, verbose_name='Заказчик (ФИО)')),
                ('zakazchik_telefon', models.CharField(blank=True, max_length=20, verbose_name='Телефон заказчика')),
                ('adres_obekta', models.CharField(max_length=500, verbose_name='Адрес объекта')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма договора, ₽')),
                ('avans_summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Сумма аванса, ₽')),
                ('srok_nachala', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('srok_okonchania', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('etap_nazvanie', models.CharField(blank=True, max_length=255, verbose_name='Название этапа')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='Чек-лист приёмки')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=documents.models.dokument_pdf_path, verbose_name='PDF-файл')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumenty', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-data_sozdaniya'],
            },
        ),
        migrations.CreateModel(
            name='DokumentPozicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('edinica', models.CharField(default='м²', max_length=20, verbose_name='Ед. изм.')),
                ('kolvo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кол-во')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед., ₽')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozicii', to='documents.dokument')),
            ],
            options={
                'verbose_name': 'Позиция акта',
                'verbose_name_plural': 'Позиции акта',
            },
        ),
    ]
