# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dokument',
            index=models.Index(fields=['brigada', '-data_sozdaniya'], name='documents_d_brigada_be6687_idx'),
        ),
    ]
