# Generated by Django 5.0.6 on 2026-07-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_code', models.SlugField(blank=True, max_length=16, unique=True, verbose_name='Код привязки')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('status', models.CharField(choices=[('ozhidaet', 'Ожидает привязки'), ('svyazan', 'Привязан')], default='ozhidaet', max_length=20, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('brigada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунты',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOtpravka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('tip', models.CharField(choices=[('dokument', 'Документ'), ('podpis', 'Ссылка на подпись'), ('napominanie', 'Напоминание')], default='dokument', max_length=20, verbose_name='Тип')),
                ('tekst', models.CharField(blank=True, max_length=500, verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('otpravleno', 'Отправлено'), ('dostavleno', 'Доставлено'), ('prochitano', 'Прочитано'), ('oshibka', 'Ошибка')], default='otpravleno', max_length=20, verbose_name='Статус')),
                ('demo_rezhim', models.BooleanField(default=False, verbose_name='Демо-режим')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_otpravki', to='documents.dokument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Отправка в WhatsApp',
                'verbose_name_plural': 'Отправки в WhatsApp',
                'ordering': ['-data'],
            },
        ),
    ]
