# Generated by Django 5.0.6 on 2026-07-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raschet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploshad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь помещения, м²')),
                ('tip_remonta', models.CharField(choices=[('econom', 'Эконом'), ('komfort', 'Комфорт'), ('premium', 'Премиум')], default='komfort', max_length=10, verbose_name='Тип ремонта')),
                ('kolvo_rabochih', models.PositiveSmallIntegerField(default=1, verbose_name='Количество рабочих')),
                ('dni', models.PositiveSmallIntegerField(default=1, verbose_name='Срок выполнения, дней')),
                ('stavka_v_den', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Оплата 1 рабочему в день, ₽')),
                ('arenda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Аренда инструмента, ₽')),
                ('dostavka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка материалов, ₽')),
                ('rashodniki', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расходники (перчатки, обеды и т.п.), ₽')),
                ('nalog', models.CharField(choices=[('4', 'Самозанятый — 4%'), ('6', 'ИП УСН доходы — 6%'), ('0', 'Наличные — 0%')], default='4', max_length=2, verbose_name='Налоговый режим')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raschety', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Расчёт себестоимости',
                'verbose_name_plural': 'Расчёты себестоимости',
                'ordering': ['-data'],
            },
        ),
    ]
