# Generated by Django 5.0.6 on 2026-07-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekFNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('naznachenie', models.CharField(max_length=255, verbose_name='Назначение')),
                ('telefon_zakazchika', models.CharField(blank=True, max_length=20, verbose_name='Телефон заказчика')),
                ('email_zakazchika', models.EmailField(blank=True, max_length=254, verbose_name='Email заказчика')),
                ('status', models.CharField(choices=[('sozdan', 'Создан'), ('otpravlen', 'Пробит и отправлен'), ('oshibka', 'Ошибка')], default='sozdan', max_length=20, verbose_name='Статус')),
                ('fns_id', models.CharField(blank=True, max_length=100, verbose_name='ID чека в ФНС')),
                ('ssylka', models.URLField(blank=True, verbose_name='Ссылка на чек')),
                ('demo_rezhim', models.BooleanField(default=False, verbose_name='Демо-режим')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheki', to='core.brigada', verbose_name='Бригада')),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheki', to='documents.dokument', verbose_name='Документ-основание')),
            ],
            options={
                'verbose_name': 'Чек ФНС',
                'verbose_name_plural': 'Чеки ФНС',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='NalogOtchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('mesyats', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('dohod', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доход, ₽')),
                ('raskhod', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расход, ₽')),
                ('nalog_4', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Налог 4% (с физлиц)')),
                ('nalog_6', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Налог 6% (с ИП/юрлиц)')),
                ('status', models.CharField(choices=[('oplachen', 'Оплачен'), ('zadolzhennost', 'Задолженность')], default='zadolzhennost', max_length=20, verbose_name='Статус')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nalog_otchety', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Налоговый отчёт',
                'verbose_name_plural': 'Налоговые отчёты',
                'ordering': ['-god', '-mesyats'],
                'unique_together': {('brigada', 'god', 'mesyats')},
            },
        ),
    ]
