# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_dokument_documents_d_brigada_be6687_idx'),
        ('nalogi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chekfns',
            index=models.Index(fields=['brigada', '-data'], name='nalogi_chek_brigada_08d25b_idx'),
        ),
    ]
