# Generated by Django 5.0.6 on 2026-07-11 19:21

import django.db.models.deletion
import smety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaCen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('edinica', models.CharField(default='м²', max_length=20, verbose_name='Ед. изм.')),
                ('kategoriya', models.CharField(choices=[('demontazh', 'Демонтаж'), ('steny', 'Стены'), ('poly', 'Полы'), ('potolki', 'Потолки'), ('plitka', 'Плитка'), ('elektrika', 'Электрика'), ('santehnika', 'Сантехника'), ('okna_dveri', 'Окна и двери'), ('pokraska', 'Покраска и отделка'), ('prochee', 'Прочее')], default='prochee', max_length=20, verbose_name='Категория')),
                ('region', models.CharField(blank=True, help_text='Пусто — цена применяется по всем регионам', max_length=100, verbose_name='Регион')),
                ('cena_econom', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, эконом ₽')),
                ('cena_srednyaya', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, средняя ₽')),
                ('cena_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, премиум ₽')),
            ],
            options={
                'verbose_name': 'Позиция базы цен',
                'verbose_name_plural': 'База цен',
                'ordering': ['kategoriya', 'nazvanie'],
            },
        ),
        migrations.CreateModel(
            name='Smeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(blank=True, max_length=30, verbose_name='Номер сметы')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название сметы')),
                ('adres', models.CharField(blank=True, max_length=500, verbose_name='Адрес объекта')),
                ('zakazchik', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('urovne_cen', models.CharField(choices=[('econom', 'Эконом'), ('srednyaya', 'Средний'), ('premium', 'Премиум')], default='srednyaya', max_length=10, verbose_name='Уровень цен')),
                ('srok_dney', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок выполнения, дней')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('public', 'Опубликована')], default='draft', max_length=10, verbose_name='Статус')),
                ('public_slug', models.SlugField(blank=True, max_length=16, null=True, unique=True, verbose_name='Публичная ссылка')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=smety.models.smeta_pdf_path, verbose_name='PDF-файл')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_izmeneniya', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smety', to='core.brigada', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SmetaRabota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('edinica', models.CharField(default='м²', max_length=20, verbose_name='Ед. изм.')),
                ('kolvo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кол-во')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед., ₽')),
                ('poryadok', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('baza_cen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smety.bazacen')),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raboty', to='smety.smeta')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['poryadok', 'id'],
            },
        ),
    ]
