# Generated by Django 5.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('smety', '0002_seed_bazacen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='smeta',
            index=models.Index(fields=['brigada', '-data'], name='smety_smeta_brigada_2a2dc5_idx'),
        ),
    ]
